### ISSUE TITLE
Problems to treat data

### ISSUE THREAD

**Issue by GustavoClaude** [biopatrec/biopatrec#6]
Good morning,

In the Signal Treatment window, after I did the pre-processing step, when I pushed the Treat button, I received these error messages:

" Reference to non-existent field 'sigSeperation'.
  
  Error in ComputeSignalSeparation (line 31)
  if strcmp(sigTreated.sigSeperation.Alg,'ICA')

  Error in TreatData (line 67)
  sigTreated=ComputeSignalSeparation(sigTreated);

  Error in GUI_SigTreatment>pb_treat_Callback (line 117)
  sigTreated = TreatData(handles, sigTreated); % Treat Data

  Error in gui_mainfcn (line 96)
  feval(varargin{:});
  
  Error in GUI_SigTreatment (line 67)
  gui_mainfcn(gui_State, varargin{:});

  Error in
  @(hObject,eventdata)GUI_SigTreatment('pb_treat_Callback',hObject,eventdata,guidata(hObject))
 
  Error while evaluating uicontrol Callback"

I followed the steps described in Startup Guide and in the video from YouTube chanel. I am using the Matlab 2013b on Win7, is it a problema with the version Matlab? Can you help me? Thank You.

**Comment by maxoc** [comment]
Hi Gustavo, this is a know issue in the TRE version due the addition of signal separation algorithms which wasn't properly done. We have fixed this problem in the next version that is about to come out. If are in a hurry the easiest fix would be to download the TVA version and use that feature (treat folder) there. Otherwise the new version (FRA) will come out in a couple of weeks.

**Comment by GustavoClaude** [comment]
Thank you very much. I will download the TVA version and when the new version come out, I update it. Thank you again.

**Comment by GustavoClaude** [comment]
Sorry, but I couldn't find the TVA version to download in the repository. Could you show me the link to do it, please? Thank you.

**Comment by MB-Kristoffersen** [comment]
Hi Gustavo,

You can find it here
https://github.com/biopatrec/biopatrec/tree/v2.0/BioPatRec_TVA

Best Regards
Morten

2016-05-02 14:21 GMT+02:00 GustavoClaude <notifications@github.com>:

**Comment by GustavoClaude** [comment]
Thank you, I could download the TVA version and now I'm using the BioPatRec.
