### ISSUE TITLE
Read error of dataset "6mov8chFUS"

### ISSUE THREAD

**Issue by yudeshui** [biopatrec/biopatrec#8]
I have downloaded the dataset "6mov8chFUS", and use python to load these data.
The code is :
`import scipy.io as sio `
`a=sio.loadmat('./1.mat')`

When I read the file 7.mat, there got an error.
However, the other .mat files are loaded normally.

Error messsage:
/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio.pyc in loadmat(file_name, mdict, appendmat, **kwargs)
    124     variable_names = kwargs.pop('variable_names', None)
    125     MR = mat_reader_factory(file_name, appendmat, **kwargs)
--> 126     matfile_dict = MR.get_variables(variable_names)
    127     if mdict is not None:
    128         mdict.update(matfile_dict)

/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio5.pyc in get_variables(self, variable_names)
    286                 continue
    287             try:
--> 288                 res = self.read_var_array(hdr, process)
    289             except MatReadError as err:
    290                 warnings.warn(

/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio5.pyc in read_var_array(self, header, process)
    246            `process`.
    247         '''
--> 248         return self._matrix_reader.array_from_header(header, process)
    249 
    250     def get_variables(self, variable_names=None):

mio5_utils.pyx in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy/io/matlab/mio5_utils.c:6021)()

mio5_utils.pyx in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy/io/matlab/mio5_utils.c:5664)()

mio5_utils.pyx in scipy.io.matlab.mio5_utils.VarReader5.read_struct (scipy/io/matlab/mio5_utils.c:8581)()

mio5_utils.pyx in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix (scipy/io/matlab/mio5_utils.c:5252)()

mio5_utils.pyx in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy/io/matlab/mio5_utils.c:5448)()

mio5_utils.pyx in scipy.io.matlab.mio5_utils.VarReader5.read_real_complex (scipy/io/matlab/mio5_utils.c:6445)()

mio5_utils.pyx in scipy.io.matlab.mio5_utils.VarReader5.read_numeric (scipy/io/matlab/mio5_utils.c:3949)()

mio5_utils.pyx in scipy.io.matlab.mio5_utils.VarReader5.read_element (scipy/io/matlab/mio5_utils.c:3657)()

streams.pyx in scipy.io.matlab.streams.ZlibInputStream.read_string (scipy/io/matlab/streams.c:2711)()

streams.pyx in scipy.io.matlab.streams.ZlibInputStream.read_into (scipy/io/matlab/streams.c:2513)()

streams.pyx in scipy.io.matlab.streams.ZlibInputStream._fill_buffer (scipy/io/matlab/streams.c:2397)()

error: Error -3 while decompressing: incorrect data check.

Thanks:)

**Comment by casualformality** [comment]
It appears there was a checksum error in the file. Opening it in MATLAB and saving it again seems to have fixed the problem.

The fixed file has been uploaded. Please update your local copy and try again and report back.
Thanks!

**Comment by yudeshui** [comment]
@casualformality  
I update and reload the data. All files are loaded normally.
Thanks :)
